### ISSUE TITLE
Name conflict

### ISSUE THREAD

**Issue by sh0rez** [bwplotka/bingo#10]
The name `bingo` was previously used in the Go community for https://github.com/saibing/bingo, a very early LSP implementation.

Given that this project is now flagged deprecated as `gopls` matures, I don't think this is too much of an issue, only users that historically still have bingo binaries will be affected by this.

Feel free to close immediately, just a heads up :)

**Comment by bwplotka** [comment]
Thanks for heads up! I think I can inherit the name (: There should be no issues even if there is a clash. Thanks anyway :heart: :
