### ISSUE TITLE
Parsing of devel Go version fails

### ISSUE THREAD

**Issue by martin-sucha** [bwplotka/bingo#131]
**`bingo version` output**:

```
v0.7
```

**`go version` output**:

```
go version devel go1.21-02d8ebda83 Mon Feb 6 22:13:07 2023 +0000 linux/amd64
```

**What happened**:

When running a bingo command with a development version of Go, Bingo commands fail.
Even simple `bingo version` prints the following error:

```
Error: version command failed: parse go version: unexpected go version format
```

**What you expected to happen**:

Bingo parses the version.

**How to reproduce it (as minimally and precisely as possible)**:

1. [Compile a development version of Go](https://go.dev/doc/install/source) (e.g. checkout the Go sources, `cd src`, `./make.bash`
2. Make the dev Go version reachable from PATH
3. Run `bingo version`

**Anything else we need to know**:

There is an additional `devel` token in the `go version` output, so parseGoVersion needs to be adjusted.

**Comment by bwplotka** [comment]
Yup, bug to fix, thanks for proposing fix, commented.
