### ISSUE TITLE
Fix ./bingo/README.md: variables.go was never supported. 

### ISSUE THREAD

**Issue by kishaningithub** [bwplotka/bingo#141]
**`bingo version` output**:
v0.8

**`go version` output**:
go version go1.20.4 darwin/arm64

**What happened**:
`variables.go` file is not generated by bingo as documented in README

**What you expected to happen**:
variables.go should be generated

**How to reproduce it (as minimally and precisely as possible)**:
- Use bingo in a new project

**Examples**:
You can see it in this repo itself. If you look at the code below you see the README documentation generated by bingo https://github.com/bwplotka/bingo/blob/fd11be5060a91cd566699904a8a58aa9973c00f6/.bingo/README.md?plain=1#L9
but if you look at [the directory](https://github.com/bwplotka/bingo/tree/fd11be5060a91cd566699904a8a58aa9973c00f6/.bingo) the `variables.go` file is not present.

**Comment by aimuz** [comment]
This does not seem to be supported

**Comment by kishaningithub** [comment]
@bwplotka I was hoping that this would fix the following observation (screenshot and link below)

https://github.com/jeroenrinzema/psql-wire/pull/58#discussion_r1198710199
<img width="787" alt="image" src="https://github.com/bwplotka/bingo/assets/763760/cd29a702-4300-4dc8-8b6c-ac0cf95b8236">
