### ISSUE TITLE
Bug: Go 1.21.0

### ISSUE THREAD

**Issue by tamalsaha** [bwplotka/bingo#143]
I tried to install in Go 1.21.0 and it fails. Please see below:

```
> docker run -it golang:1.21.0 bash

root@199187857bfb:/go# go install github.com/bwplotka/bingo@latest
go: downloading github.com/bwplotka/bingo v0.8.0
go: downloading github.com/Masterminds/semver v1.5.0
go: downloading github.com/efficientgo/core v1.0.0-rc.0
go: downloading github.com/oklog/run v1.1.0
go: downloading golang.org/x/mod v0.5.1
go: downloading mvdan.cc/sh/v3 v3.4.3
go: downloading golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1
go: downloading golang.org/x/sys v0.0.0-20220330033206-e17cdc41300f
go: downloading golang.org/x/sync v0.0.0-20210220032951-036812b2e83c
go: downloading golang.org/x/term v0.0.0-20210927222741-03fcf44c2211

root@199187857bfb:/go# bingo get -l github.com/bwplotka/bingo
Bingo not used before here, creating directory for pinned modules for you at .bingo
Error: get command failed: get: bingo.mod: getting github.com/bwplotka/bingo: create empty tmp mod file: parse: /go/.bingo/bingo-e.tmp.mod:3: invalid go version '1.21.0': must match format 1.23
```

**Comment by rudo-thomas** [comment]
Fix here for those who need it:
https://github.com/bwplotka/bingo/pull/144

**Comment by eriksw** [comment]
@bwplotka Would you please tag a release so that it's easier to install a version that works with go 1.21, now that #145 is merged?

**Comment by KenxinKun** [comment]
Indeed a release with the #145 fix would be super appreciated @bwplotka 🙏

I have tested by cloning/building the repo and using the binary with `bingo get go.uber.org/mock/mockgen@v0.3.0` and it works like a charm now ❤️

**Comment by lyda** [comment]
Yes please, `go install github.com/bwplotka/bingo@main` is a little too cutting edge for me!

**Comment by bwplotka** [comment]
Yes! 

Asked @saswatamcode to help this week in releasing, Thanks!

**Comment by bwplotka** [comment]
I will close this as it's fixed in latest at least, thanks!

**Comment by saswatamcode** [comment]
Released as well: https://github.com/bwplotka/bingo/releases/tag/v0.9.0
