### ISSUE TITLE
Error on sourcing .bingo/variables.env files

### ISSUE THREAD

**Issue by kakkoyun** [bwplotka/bingo#40]
`.bingo/variables.env` is using `local` outside a function it causes an error on certain systems.

```console
$ source .bingo/variables.env
.bingo/variables.env: line 4: local: can only be used in a function
```

See also https://app.circleci.com/pipelines/github/thanos-io/thanos/2025/workflows/74888d11-3a8e-413b-83e5-0a4928b4d59e/jobs/10145

**Comment by asutula** [comment]
Causing problems in Github actions as well running in their `ubuntu-latest`

**Comment by asutula** [comment]
https://github.com/textileio/powergate/runs/951417780?check_suite_focus=true#step:7:9
