### ISSUE TITLE
Support build tags

### ISSUE THREAD

**Issue by metalmatze** [bwplotka/bingo#46]
I have the problem of wanting to import a build tool that has a build tag `tools`.
https://github.com/observatorium/deployments/blob/f460944fe1a95ff062886c95f04a654d3c26910c/Makefile

Not sure how that is supported right now. I'll add it manually and overwrite the build command in the Makefile.

**Comment by metalmatze** [comment]
I tried adding this to bingo myself and I think it requires a bit more thought.
It seems that all dependencies are written as mod files to disk and then there's essentially no other shared state where we could communicate some additional build tags from the CLI to the generated Makefile. :thinking:

**Comment by bwplotka** [comment]
The only persistency is in `.mod` file

How I would do is that I would add flag `tags` to `get` that has package in it, and I would put `-tags` (or any other build flags) in comment for direct `require`.

Bingo uses this already for  package path, but we can add build flags on top (e.g tools)

Help wanted. 🤗

**Comment by bwplotka** [comment]
cc @kakkoyun

**Comment by bwplotka** [comment]
Another use case: Extended Hugo support: https://github.com/gohugoio/hugo#prerequisite-tools
