### ISSUE TITLE
`-i` build flag can cause permissions issues for go installations owned by `root`

### ISSUE THREAD

**Issue by lukasbob** [bwplotka/bingo#50]
Various issues suggest that using the `-i` build flag is no longer necessary - e.g. https://github.com/golang/go/issues/37962#issuecomment-601737570. Further, there is a pending issue that will deprecate the flag in go1.16, removing it in 1.17: https://github.com/golang/go/issues/41696.

Would it be possible to remove that build flag to make the out-of-the-box experience with `bingo get` smoother?

For now I have worked around the issue with `chown -R <user> /usr/local/go` (or wherever the installation lives).

https://github.com/bwplotka/bingo/blob/master/pkg/runner/runner.go#L212

**Comment by bwplotka** [comment]
Thanks for tip! Yes let's rethink this then, we have to remove `-i` seems like (:

**Comment by bwplotka** [comment]
Done (:
