### ISSUE TITLE
Install location different between bingo get and makefile

### ISSUE THREAD

**Issue by cszatmary** [bwplotka/bingo#53]
The install location is different when installing tools with `bingo get` vs using the makefile variables. When running `bingo get` tools are installed at `.bingo`. When using the makefile variables, tools are installed at `$GOPATH/bin`. I'm wondering what the reason for this is? Would it be possible to make both methods install to the same location?

For context, I want to run `bingo get` in CI to install all required tools, and then cache all the built tools. However, if I then go to use them in my makefile they will be rebuilt, which defeats the point of caching them.

**Comment by bwplotka** [comment]
I think this might be a bug. Tools (binaries) are aways installed in `GOBIN` (and if GOBIN is missing then `GOPATH/bin`). However by default `.bingo` is used to host `.mod` files for tools pinning. 

Are you sure you can see binaries installed in `.bingo`? That's a bug then. What version of bingo you are using? (: `bingo version)

**Comment by sevein** [comment]
I've been working on a small project with a few colleagues and this behaviour was seen by two out of four people. We were all using Go 1.15 in Linux or macOS, pretty standard configuration. So strange!

**Comment by bwplotka** [comment]
Might be that GOBIN is not stable in your case? (:
Kind Regards,
Bartek Płotka (@bwplotka)

**Comment by bwplotka** [comment]
Let me if know if that's the case and if there is anything that tool could do better (:

**Comment by bwplotka** [comment]
We can reopen in that case 🤗
