### ISSUE TITLE
Weird log line: found malformed module file, removing

### ISSUE THREAD

**Issue by bwplotka** [bwplotka/bingo#54]
`Found malformed module file, removing: /home/bwplotka/Repos/bingo/.bingo/mdox.mod` - but actually nothing was removed 🔥  (:

**Comment by bwplotka** [comment]
Also no reason was stated - to fix.

**Comment by bwplotka** [comment]
Should be fixed in https://github.com/bwplotka/bingo/pull/60 🤗

**Comment by sevein** [comment]
@bwplotka, thanks! You're awesome.

**Comment by bwplotka** [comment]
Please try and give feedback (: Just triggering new release (0.3.0)

**Comment by sevein** [comment]
I've built 66e3b70987d8adc6fee3745577a195fad7a3ecde, so far so good!
