### ISSUE TITLE
errorcapture error on bingo install

### ISSUE THREAD

**Issue by asutula** [bwplotka/bingo#67]
**`bingo version` output**: none, not installed yet

**`go version` output**: go version go1.15.5 darwin/amd64

**What happened**:

When I try to install bingo, I get the following error. 

```
go get github.com/bwplotka/bingo      
# github.com/bwplotka/bingo/pkg/bingo
go/src/github.com/bwplotka/bingo/pkg/bingo/mod.go:86:4: undefined: errcapture.Close
go/src/github.com/bwplotka/bingo/pkg/bingo/mod.go:328:8: undefined: errcapture.Close
```

Indeed, the latest code in the errorcapture module doesn't have a `Close` func (there is a `Do` func). I see the bingo go.mod is targeting some specific commit of errorcapture, but maybe its not the right one? Not sure what's going on exactly.

**What you expected to happen**:

I expected to install bingo successfully.

**Comment by asutula** [comment]
Looks like the bingo go.mod is pinning the correct/older commits that have `Close()` from `github.com/efficientgo/tools`.

**Comment by asutula** [comment]
I can build bingo from source just fine.

**Comment by bwplotka** [comment]
Ups, let's see what's going on, thx for reporting.

**Comment by bwplotka** [comment]
The problem is the https://github.com/efficientgo/tools being not well released, might create issues like this. Let me fix this.

**Comment by bwplotka** [comment]
Ok, this https://github.com/bwplotka/bingo/pull/68 should fix this particular problem, but... it's scary that go build does not care about pinned version 🤔

**Comment by asutula** [comment]
Yea, strange. Thanks for the fix, Bingo is great!
