### ISSUE TITLE
Error running with Go pre-releases

### ISSUE THREAD

**Issue by sevein** [bwplotka/bingo#70]
**`bingo version` output**:

```
v0.3.1
```

**`go version` output**:

```
go version go1.16rc1 linux/amd64
```

**What happened**:

bingo quits with the following error, returned by *Runner:

```
Error: list command failed: Invalid Semantic Version
```

**What you expected to happen**:

* The underlying error details are shared to ease troubleshooting, and
* `parseGoVersion` does not fail to capture X.Y.Z string used to build the *semver.Version

**How to reproduce it (as minimally and precisely as possible)**:

1. Install go1.16rc1
2. Run `bingo list`

**Logs (use `bingo get -v <thing you do>` for verbose output)**:

```
Error: Invalid Semantic Version
get command failed
main.main
	/home/username/go/src/github.com/bwplotka/bingo/main.go:255
runtime.main
	/home/username/sdk/go1.16rc1/src/runtime/proc.go:225
runtime.goexit
	/home/username/sdk/go1.16rc1/src/runtime/asm_amd64.s:1371
exit status 1
```

**Anything else we need to know**:

I'd be happy to try to fix it. This [initial attempt](https://gist.github.com/sevein/c7e3948f35d7f6f86f32dfddf136b37e) worked for me but feel free to suggest changes.

There may be more issues when using go1.16, e.g. I've seen this:

```
bingo get github.com/bufbuild/buf/cmd/buf@v0.36.0
Error: get command failed: get: buf.mod: getting github.com/bufbuild/buf/cmd/buf@v0.36.0: install: go: github.com/bufbuild/buf@v0.36.0: missing go.sum entry; to add it:
	go mod download github.com/bufbuild/buf
: exit 1
```

**Comment by codefromthecrypt** [comment]
I'm also getting the issue you mentioned about go1.16. There may be some snags here left indeed

**Comment by codefromthecrypt** [comment]
https://github.com/textileio/powergate/commit/c8d5cc71711d951694536f7228e5c9d0ce8b14f7 seems related

**Comment by bwplotka** [comment]
Nice, I did not try bingo with go1.16, so there might be some funky stuff
happening.

Will look in free moment, help wanted as well! It looks like they changed
the version format printed by Go command (:

Kind Regards,
Bartek Płotka (@bwplotka)

**Comment by codefromthecrypt** [comment]
@sevein @jsign @bwplotka can you take a look at what @nacx #74? would be nice to get things out of manual adjustments especially as so many projects move to go 1.16

**Comment by bwplotka** [comment]
Yup, will take a look today (:

**Comment by bwplotka** [comment]
Fixed. Please try https://github.com/bwplotka/bingo/releases/tag/v0.4.0 🚀 Thanks @codefromthecrypt and @nacx for enormous help.

**Comment by sevein** [comment]
@codefromthecrypt @bwplotka, do you think v0.4.0 will be able to parse Go's version from a string like `go1.16rc1`? That was one issue I tried to raise here but it doesn't seem like it's been addressed. I had to [change](https://gist.github.com/sevein/c7e3948f35d7f6f86f32dfddf136b37e) the way parseGoVersion works to make that possible when using v0.3.1.

**Comment by bwplotka** [comment]
Uuuuups, yea we don't checked "pre-release". Do you mind porting your fix on master? 🤗  Let me reopen then.
