### ISSUE TITLE
Some files generated by bingo have the execution bit

### ISSUE THREAD

**Issue by sevein** [bwplotka/bingo#77]
**`bingo version` output**:
v0.4.0

**`go version` output**:
go version go1.16.2 linux/amd64

**What happened**:
Some files generated by bingo are created with the execution bit.

```
$ ls -lha .bingo/
total 32K
drwxrwxr-x 2 username username 4,0K abr  6 18:47 .
drwxrwxr-x 3 username username 4,0K abr  6 18:47 ..
-rwxrwxr-x 1 username username  116 abr  6 18:47 .gitignore........... ←
-rw-rw-r-- 1 username username  158 abr  6 18:47 golangci-lint.mod
-rwxrwxr-x 1 username username  148 abr  6 18:47 go.mod............... ←
-rwxrwxr-x 1 username username  820 abr  6 18:47 README.md............ ←
-rw-rw-r-- 1 username username  420 abr  6 18:47 variables.env
-rw-rw-r-- 1 username username 1,2K abr  6 18:47 Variables.mk
```

**What you expected to happen**:
Generated files don't have the execution bit when unneeded.

**How to reproduce it (as minimally and precisely as possible)**:
1. Start new Go project,
2. Run `bingo get github.com/golangci/golangci-lint/cmd/golangci-lint`
3. Run `ls -lha .bingo`

**Logs (use `bingo get -v <thing you do>` for verbose output)**:
N/A

**Anything else we need to know**:
N/A

**Comment by sevein** [comment]
@bwplotka I'd be happy to investigate a fix if you think this should be solved.

**Comment by bwplotka** [comment]
Totally! It should be easy to fix - just ensure we have correct perms when creating those files. Help wanted! 🤗
