### ISSUE TITLE
go build errors after upgrading go from 1.15 to 1.16

### ISSUE THREAD

**Issue by aws5295** [bwplotka/bingo#91]
**`bingo version` output**: `v0.4.3`

**`go version` output**: `go version go1.16.5 linux/amd64`

**What happened**:
The usage instructions list 2 different ways to use the tool:
> `go build -modfile .bingo/<tool>.mod -o=$GOBIN/<tool>-<version>`
or
`bingo get <tool>`

We prefer to use the first way (`go build`) but it abruptly stopped working after we upgraded go from 1.15 to 1.16.
The second way does still work.

**What you expected to happen**:
`go build -modfile .bingo/tool.mod -o=$GOBIN/<tool>-<version>`  will build the specified tool.

**How to reproduce it (as minimally and precisely as possible)**:
```
λ bingo get pprof@v0.0.0-20180301010423-e8d30eee164b

λ cat .pprof.mod
module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.16

require github.com/google/pprof v0.0.0-20180301010423-e8d30eee164b

λ go build -modfile ./pprof.mod -o=$GOBIN/pprof-foo
go: github.com/google/pprof@v0.0.0-20180301010423-e8d30eee164b: missing go.sum entry; to add it:
        go mod download github.com/google/pprof
```

**Logs (use `bingo get -v <thing you do>` for verbose output)**:
Here are the logs from `bingo get -v` which does work, if they are helpful:

```
λ bingo get -v pprof@v0.0.0-20180301010423-e8d30eee164b
getting target github.com/google/pprof@v0.0.0-20180301010423-e8d30eee164b (module github.com/google/pprof )
exec 'go list -modfile=/home/ubuntu/co/backend/.bingo/pprof.tmp.mod -mod=mod -f={{.Name}} github.com/google/pprof'
exec 'go build -modfile=/home/ubuntu/co/backend/.bingo/pprof.tmp.mod -o=/home/ubuntu/co/backend/go/bin/pprof-v0.0.0-20180301010423-e8d30eee164b github.com/google/pprof'
```

**Comment by bwplotka** [comment]
Thanks for reporting. You are right, we fixed bingo but forgot to update docs. You need to add ` -mod=mod` to go build to make it work for newer Go (: Will fix docs, thanks!

**Comment by aws5295** [comment]
Thanks for the response!
Just wanted to confirm that providing the `-mod=mod` flag to go build did resolve this.
